version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend


